/**
 * Public NODAYSIDLE showcase data
 * Home surface is the four flagship chapters only.
 */

/** @typedef {'voice-input' | 'notes-knowledge' | 'native-utilities' | 'workflow-systems' | 'browser-tools'} Category */
/** @typedef {'public' | 'private'} Visibility */

/**
 * @typedef {Object} Project
 * @property {string} slug
 * @property {string} name
 * @property {string} [navLabel]
 * @property {string} [kicker]
 * @property {string} [loop]
 * @property {string} [ctaLabel]
 * @property {string} [ctaHref]
 * @property {string} type
 * @property {'macOS' | 'Android'} platform
 * @property {string[]} stack
 * @property {string} status
 * @property {string} artifact
 * @property {string} release
 * @property {string} repo
 * @property {string | null} download
 * @property {string | null} checksum
 * @property {string} headline
 * @property {string} summary
 * @property {string[]} proof
 * @property {string[]} features
 * @property {'shipped'} maturity
 * @property {string} dataBoundary
 * @property {string} updated
 * @property {string | null} screenshotPath
 * @property {string | null} screenshotAlt
 * @property {string | null} screenshotSource
 * @property {string} accent
 * @property {Category} category
 * @property {Visibility} visibility
 * @property {string} story
 */

/** @type {Project[]} */
export const projects = [
  {
    slug: 'nodaysidle-cascade-v3',
    name: 'Cascade V3',
    navLabel: 'Cascade V3',
    kicker: 'macOS 13+ · Tauri 2',
    loop: 'One DeepSeek call. A local compiler writes PRD, ARD, TRD, TASKS, AGENTS. Not iOS.',
    ctaLabel: 'GitHub',
    ctaHref: 'https://github.com/nodaysidle/nodaysidle-cascade-v3',
    type: 'Contract-driven software planning app',
    platform: 'macOS',
    stack: ['Tauri', 'Rust', 'TypeScript'],
    status: 'active public system',
    artifact: 'Source repository',
    release: 'https://github.com/nodaysidle/nodaysidle-cascade-v3',
    repo: 'https://github.com/nodaysidle/nodaysidle-cascade-v3',
    download: null,
    checksum: null,
    headline: 'One idea. Five contracts.',
    summary: 'One DeepSeek call. A local compiler writes PRD, ARD, TRD, TASKS, AGENTS. Not iOS.',
    proof: ['Public repository', 'Structured contract output', 'Flagship workflow system'],
    features: [
      'One DeepSeek call drives the cascade',
      'Local compiler writes five markdown contract files',
      'Outputs PRD, ARD, TRD, TASKS, and AGENTS',
      'macOS 13+ Tauri / Rust / TypeScript',
      'No iOS build',
      'Source on GitHub — no DMG release yet',
    ],
    maturity: 'shipped',
    dataBoundary: 'local-first workflow with model-assisted meaning extraction',
    updated: '2026-09-01',
    screenshotPath: '/screenshots/cascade-v3.png',
    screenshotAlt: 'NODAYSIDLE Cascade V3 application screenshot',
    screenshotSource: null,
    accent: '#C8FF00',
    category: 'workflow-systems',
    visibility: 'public',
    story: 'One idea in. Five agent-ready markdown contracts out. Structure before code.',
  },
  {
    slug: 'nodaysidle-voice-anywhere-v2',
    name: 'Voice Anywhere',
    navLabel: 'Voice Anywhere',
    kicker: 'Android 12+',
    loop: 'Tap. STT. SET/PST when Accessibility is bound. IME paste when it isn’t. 60dp stadium. Overlay allow for the pill. First Xiaomi Accessibility enable still waits 15s.',
    ctaLabel: 'Download APK',
    ctaHref: 'https://github.com/nodaysidle/nodaysidle-voice-anywhere-v2/releases/download/v0.4.0/VoiceAnywhere-0.4.0.apk',
    type: 'Android overlay dictation',
    platform: 'Android',
    stack: ['Kotlin'],
    status: 'active public product',
    artifact: 'Android APK 0.4.0',
    release: 'https://github.com/nodaysidle/nodaysidle-voice-anywhere-v2/releases/tag/v0.4.0',
    repo: 'https://github.com/nodaysidle/nodaysidle-voice-anywhere-v2',
    download: 'https://github.com/nodaysidle/nodaysidle-voice-anywhere-v2/releases/download/v0.4.0/VoiceAnywhere-0.4.0.apk',
    checksum: null,
    headline: 'Overlay pill. Words at the cursor.',
    summary: 'Tap. STT. SET/PST when Accessibility is bound. IME paste when it isn’t.',
    proof: ['Public repository', 'v0.4.0 APK release', 'Android 12+'],
    features: [
      'Overlay pill → STT → insert at cursor',
      'SET/PST when Accessibility is BOUND',
      'IME paste when the bind is DEAD',
      'ACCESS tile states: BOUND / DEAD / ENABLE',
      '60dp stadium overlay pill',
      'First Xiaomi Accessibility enable waits 15s',
    ],
    maturity: 'shipped',
    dataBoundary: 'on-device overlay with configured speech path',
    updated: '2026-09-01',
    screenshotPath: null,
    screenshotAlt: null,
    screenshotSource: null,
    accent: '#C8FF00',
    category: 'voice-input',
    visibility: 'public',
    story: 'Android overlay dictation. Words land at the cursor. No iOS.',
  },
  {
    slug: 'nodaysidle-vois',
    name: 'NODAYSIDLE Voice',
    navLabel: 'Voice',
    kicker: 'macOS 14+ · Apple silicon',
    loop: 'Silent capsule. Deepgram live words in-capsule. Finals only. EN / IT / SL. Pill hides after talk.',
    ctaLabel: 'Download DMG',
    ctaHref: 'https://github.com/nodaysidle/nodaysidle-vois/releases/download/v0.2.0/NODAYSIDLE-Voice-0.2.0.dmg',
    type: 'Native macOS menu-bar dictation',
    platform: 'macOS',
    stack: ['Swift', 'SwiftUI', 'AppKit'],
    status: 'active public product',
    artifact: 'macOS DMG 0.2.0',
    release: 'https://github.com/nodaysidle/nodaysidle-vois/releases/tag/v0.2.0',
    repo: 'https://github.com/nodaysidle/nodaysidle-vois',
    download: 'https://github.com/nodaysidle/nodaysidle-vois/releases/download/v0.2.0/NODAYSIDLE-Voice-0.2.0.dmg',
    checksum: null,
    headline: 'Hold Control-Space. Speak. Text lands.',
    summary: 'Silent capsule. Deepgram live words in-capsule. Finals only. EN / IT / SL. Pill hides after talk.',
    proof: ['Public repository', 'v0.2.0 DMG release', 'Native SwiftUI menu bar'],
    features: [
      'Hold Control-Space to dictate',
      'Silent capsule with Deepgram live words',
      'Finals only — EN / IT / SL',
      'Pill hides after talk',
      'macOS 14+ Apple silicon',
      'Native SwiftUI menu-bar app',
    ],
    maturity: 'shipped',
    dataBoundary: 'depends on configured speech path',
    updated: '2026-09-01',
    screenshotPath: null,
    screenshotAlt: null,
    screenshotSource: null,
    accent: '#C8FF00',
    category: 'voice-input',
    visibility: 'public',
    story: 'Hold Control-Space. Speak. Text lands. Pill hides after talk.',
  },
  {
    slug: 'synapse-notes',
    name: 'Synapse Notes',
    navLabel: 'Synapse Notes',
    kicker: 'Android',
    loop: 'Title is the first sentence. Graph is a screen you open — keyword edges. List search is text match.',
    ctaLabel: 'Download APK',
    ctaHref: 'https://github.com/nodaysidle/synapse-notes/releases/download/v0.4.3/synapse-notes-0.4.3-debug.apk',
    type: 'Voice-first note system',
    platform: 'Android',
    stack: ['TypeScript', 'React', 'Capacitor'],
    status: 'active public product',
    artifact: 'Android APK 0.4.3',
    release: 'https://github.com/nodaysidle/synapse-notes/releases/tag/v0.4.3',
    repo: 'https://github.com/nodaysidle/synapse-notes',
    download: 'https://github.com/nodaysidle/synapse-notes/releases/download/v0.4.3/synapse-notes-0.4.3-debug.apk',
    checksum: null,
    headline: 'Speak. Transcript. Image. Home.',
    summary: 'Title is the first sentence. Graph is a screen you open — keyword edges. List search is text match.',
    proof: ['Public repository', 'v0.4.3 APK release', 'Capacitor Android'],
    features: [
      'Speak → transcribe → embed → image → Home',
      'Title is the first sentence',
      'Graph is a screen you open with keyword edges',
      'List search is text match',
      'Capacitor Android',
      'No iOS build',
    ],
    maturity: 'shipped',
    dataBoundary: 'hybrid app workflow',
    updated: '2026-09-01',
    screenshotPath: null,
    screenshotAlt: null,
    screenshotSource: null,
    accent: '#C8FF00',
    category: 'notes-knowledge',
    visibility: 'public',
    story: 'Speak. Transcript. Image. Home. Graph is a screen you open — not a pipeline step.',
  },
  {
    slug: 'nodaysidle-cistilka',
    name: 'Cistilka',
    type: 'Disk space analyzer',
    platform: 'macOS',
    stack: ['Swift', 'SwiftUI'],
    status: 'active public product',
    artifact: 'macOS release',
    release: 'https://github.com/nodaysidle/nodaysidle-cistilka/releases',
    repo: 'https://github.com/nodaysidle/nodaysidle-cistilka',
    download: 'https://github.com/nodaysidle/nodaysidle-cistilka/releases',
    checksum: null,
    headline: 'Native macOS disk space analyzer focused on safe cleanup.',
    summary: 'A practical utility that makes disk usage legible and cleanup decisions safer without bloated system-junk theatrics.',
    proof: ['Public repository', 'Strong utility positioning', 'Native-first product'],
    features: [
      'Clear disk usage visibility',
      'Safe-cleanup framing instead of risky deletion theater',
      'Represents the NODAYSIDLE utility lane cleanly',
      'Native product fit for macOS users',
      'Focused scope instead of bundled nonsense',
      'Strong example of function before flash',
    ],
    maturity: 'shipped',
    dataBoundary: 'local',
    updated: '2026-09-01',
    screenshotPath: null,
    screenshotAlt: null,
    screenshotSource: null,
    accent: '#FFB86A',
    category: 'native-utilities',
    visibility: 'public',
    story: 'This is the utility philosophy in plain form: solve a real local problem clearly, cleanly, and without unnecessary noise.',
  },
  {
    slug: 'pocket-drafts',
    name: 'Pocket Drafts',
    type: 'Private capture utility',
    platform: 'macOS',
    stack: ['Swift', 'SwiftUI', 'SwiftData'],
    status: 'active public product',
    artifact: 'Source repository',
    release: 'https://github.com/nodaysidle/pocket-drafts/releases',
    repo: 'https://github.com/nodaysidle/pocket-drafts',
    download: 'https://github.com/nodaysidle/pocket-drafts/releases',
    checksum: null,
    headline: 'Fast, private note capture from the macOS menu bar.',
    summary: 'A smaller expression of the same capture-first instinct: get the thought down quickly, locally, and without friction.',
    proof: ['Public repository', 'Menu bar workflow', 'Local-first capture utility'],
    features: [
      'Fast private note capture',
      'Menu bar workflow',
      'Local-first storage',
      'Minimal interface overhead',
      'Small but sharp utility shape',
      'Fits the NODAYSIDLE capture family',
    ],
    maturity: 'shipped',
    dataBoundary: 'local',
    updated: '2026-09-01',
    screenshotPath: null,
    screenshotAlt: null,
    screenshotSource: null,
    accent: '#C8FF00',
    category: 'notes-knowledge',
    visibility: 'public',
    story: 'Not every product has to be broad. Some NODAYSIDLE tools exist to remove one point of friction from everyday work and do it well.',
  },
  {
    slug: 'nodaysrecording',
    name: 'NODAYSRECORDING',
    type: 'Screen recording tool',
    platform: 'macOS',
    stack: ['Swift', 'SwiftUI'],
    status: 'active public product',
    artifact: 'macOS release',
    release: 'https://github.com/nodaysidle/nodaysrecording/releases',
    repo: 'https://github.com/nodaysidle/nodaysrecording',
    download: 'https://github.com/nodaysidle/nodaysrecording/releases',
    checksum: null,
    headline: 'Local-first macOS screen recorder for polished demos and tutorials.',
    summary: 'A utility for communicating software clearly through recorded proof, not just screenshots and claims.',
    proof: ['Public repository', 'Demo-oriented utility', 'Native macOS release surface'],
    features: [
      'Local-first screen recording',
      'Useful for demos and product proof',
      'Supports public-facing communication around software',
      'Simple workflow over cluttered production suites',
      'Fits the utility layer of the ecosystem',
      'Designed around practical output quality',
    ],
    maturity: 'shipped',
    dataBoundary: 'local',
    updated: '2026-09-01',
    screenshotPath: null,
    screenshotAlt: null,
    screenshotSource: null,
    accent: '#7DD3FC',
    category: 'native-utilities',
    visibility: 'public',
    story: 'Software needs proof. Recording tools matter because they make products explainable, demonstrable, and easier to trust.',
  },
  {
    slug: 'orbit-browser',
    name: 'Orbit Browser',
    type: 'Focused browser experiment',
    platform: 'macOS',
    stack: ['Tauri', 'Rust', 'WKWebView'],
    status: 'public product line',
    artifact: 'macOS release',
    release: 'https://github.com/nodaysidle/orbit-browser/releases/tag/v1.0.6',
    repo: 'https://github.com/nodaysidle/orbit-browser',
    download: 'https://github.com/nodaysidle/orbit-browser/releases/download/v1.0.6/Orbit_1.0.6_aarch64.dmg',
    checksum: '748014773343585c19398e381dd82051d89195a20eb2bcd2892b68a5836a59e3',
    headline: 'Focused macOS browser built for quiet, distraction-light browsing.',
    summary: 'A browser experiment that reflects the same recurring NODAYSIDLE preference for less noise, more intent, and native control.',
    proof: ['Public release', 'Native browser experimentation', 'Focused browsing direction'],
    features: [
      'Quiet browsing orientation',
      'Native-first approach rather than heavy Electron stack',
      'Keyboard and focus-oriented behavior',
      'Cleaner reading and navigation intent',
      'Represents a smaller but meaningful product branch',
      'Shows range without breaking the overall worldview',
    ],
    maturity: 'shipped',
    dataBoundary: 'local',
    updated: '2026-06-25',
    screenshotPath: '/screenshots/orbit-browser.png',
    screenshotAlt: 'Orbit Browser dark UI screenshot',
    screenshotSource: null,
    accent: '#78C7EA',
    category: 'browser-tools',
    visibility: 'public',
    story: 'Even the browser work points in the same direction: focused software, tighter boundaries, and tools that reduce noise rather than amplify it.',
  },
  {
    slug: 'cliprail',
    name: 'ClipRail',
    type: 'Clipboard history utility',
    platform: 'macOS',
    stack: ['Swift', 'SwiftUI'],
    status: 'public utility',
    artifact: 'macOS release',
    release: 'https://github.com/nodaysidle/cliprail/releases/tag/v1.2.0',
    repo: 'https://github.com/nodaysidle/cliprail',
    download: 'https://github.com/nodaysidle/cliprail/releases/download/v1.2.0/ClipRail-v1.2.0-macos.zip',
    checksum: null,
    headline: 'Local text-only clipboard history for the macOS menu bar.',
    summary: 'A small utility with a very clear job: preserve useful copied text without turning the clipboard into surveillance software.',
    proof: ['Public release', 'Zero network utility', 'Minimal menu bar workflow'],
    features: [
      'Text-only clipboard history',
      'Local-first behavior',
      'Searchable lightweight recall',
      'Small sharp utility footprint',
      'Privacy-aware by design',
      'Fits the NODAYSIDLE utility family cleanly',
    ],
    maturity: 'shipped',
    dataBoundary: 'local',
    updated: '2026-07-01',
    screenshotPath: null,
    screenshotAlt: null,
    screenshotSource: null,
    accent: '#C8FF00',
    category: 'native-utilities',
    visibility: 'public',
    story: 'The ecosystem is not only about ambitious systems. It is also about useful low-friction tools that earn their place through daily reliability.',
  },
  {
    slug: 'nodaysidian',
    name: 'Nodaysidian',
    type: 'Knowledge graph for Markdown notes',
    platform: 'macOS',
    stack: ['Swift', 'SwiftUI', 'Core Data'],
    status: 'public knowledge tool',
    artifact: 'macOS release',
    release: 'https://github.com/nodaysidle/nodaysidian/releases/tag/v0.1.0',
    repo: 'https://github.com/nodaysidle/nodaysidian',
    download: 'https://github.com/nodaysidle/nodaysidian/releases/download/v0.1.0/Nodaysidian.dmg',
    checksum: null,
    headline: 'Native macOS knowledge graph for Markdown notes.',
    summary: 'A local-first graph surface for notes that extends the same memory and structure interest seen across your broader work.',
    proof: ['Public repository', 'Native knowledge graph direction', 'Markdown-centric workflow'],
    features: [
      'Knowledge graph exploration',
      'Markdown-first note structure',
      'Local semantic linking direction',
      'Graph and note workspace interaction',
      'A stronger native knowledge-system thesis',
      'Keeps memory and structure local',
    ],
    maturity: 'shipped',
    dataBoundary: 'local',
    updated: '2026-06-22',
    screenshotPath: null,
    screenshotAlt: null,
    screenshotSource: null,
    accent: '#C8FF00',
    category: 'notes-knowledge',
    visibility: 'public',
    story: 'This is another expression of the same idea: information should stay explorable, structurally meaningful, and under the user’s control.',
  },
];

/** Home page chapters — exactly these four, this order. */
export const featuredSlugs = [
  'nodaysidle-cascade-v3',
  'nodaysidle-voice-anywhere-v2',
  'nodaysidle-vois',
  'synapse-notes',
];

export function getFeaturedProjects() {
  return featuredSlugs.map((slug) => getProject(slug)).filter(Boolean);
}

export function getProject(slug) {
  return projects.find((project) => project.slug === slug);
}

export function formatChecksum(hash) {
  if (!hash || typeof hash !== 'string') return '—';
  return `${hash.slice(0, 12)}…${hash.slice(-10)}`;
}
